### PR TITLE
Add reference testcases for array handling

### PR DESCRIPTION
**Pull request by wichert**
As preparation for zserio 2.5 support I’ve added a couple of extra tests to make sure I don’t break anything.

@aignas I'm not entirely happy with how much extra bazel config this will add if we add more testcases. Do you see a good way to simplify that? We could have a single Python command output multiple files, and have one `go_test` target that runs over all tests perhaps?

### CODE REVIEW

**Comment by aignas** [comment]
How would everything look like if we separate the array tests under `test/array/<name>` so that each folder has a single `go_test` target? The main idea would be to leave most of the work to be done by `gazelle` and instead of adding things to the `reference` folder, we colud create a separate directory per `.py` data file.

**Comment by wichert** [comment]
I'm probably more tempted to have one test binary target - I suspect that will give better coverage data as well.

Are you implying that you can't have more than one test binary per folder with gazelle?

**Comment by aignas** [comment]
You can. It is just that `gazelle` may be slightly annoying, but you can always disable gazelle if needed.

**Review by Danaozhong — APPROVED** [review]
LGTM

**Comment by aignas** [comment]
Thank you!

**Pull request merged**
