### PR TITLE
Initializes slices with proper length

### PR DESCRIPTION
**Pull request by jo-me**
Regarding https://github.com/woven-planet/go-zserio/discussions/138  this is a simple optimization that pre-initializes slices during encoding and decoding to avoid unnecessary slice resizing. 

As I still have issues setting up the local development environment the code changes are untested, but they are simple enough to be refined during PR review.

The program was tested solely for our own use cases, which might differ from yours.

Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by wichert** [comment]
Thanks! The changes look simple enough. I'm not quite sure why CI is failing here - we'll look into that.

**Comment by wichert** [comment]
Looks like there is a template error. Running `go-zserio` on the test schema is failing:

```
❯ ./bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/cmd/go-zserio/go-zserio_/go-zserio generate \
  --out - \     
  --rootpackage gen/github.com/woven-planet/go-zserio/testdata \
  --only packed_nested_array.schema \
   \
  --sql \
  test/reference/packed_nested_array/schema.zs
…
[lot of output]
…
    for index := range v.List {
        ListArrayProperties.RawArray = append(ListArrayProperties.RawArray, &v.List[index])
    }
    if delta, err := ListArrayProperties.ZserioBitSizePacked(endBitPosition); err != nil {
        return 0, err
    } else {
    endBitPosition += delta
    }

  return endBitPosition - bitPosition, nil
}

Error: generate code: write packed_nested_array: format: 161:25: expected type, found '{' (and 10 more errors)
```

**Comment by wichert** [comment]
This generated code from `UnmarshalZserioPacked` is the culprit:

```
        v.List = make([]{false packed_nested_array.schema PackableNestedStructure 0 [] [] <nil>}, 0, len(ListArrayProperties.RawArray))
        for _, elem := range ListArrayProperties.RawArray {
            v.List = append(v.List, *elem)
        }
```

**Comment by jo-me** [comment]
Oh no.. 

So, I guess 
`{{ $field.Type }}`
needs to be change to
`{{ goType $scope $field.Type }}`
or 
`{{ goType $scope $native.Type }} `

What is the difference between those?

**Comment by wichert** [comment]
There is another error in `MarshalZserio`. From the generated code:

```go
// MarshalZserio implements the zserio.Marshaler interface.
func (v *PackedPosition2DArray) MarshalZserio(w zserio.Writer) error {
// …
    PositionsArrayProperties := ztype.Array[*Position2D, ztype.ObjectArrayTraits[*Position2D]]{}
// …
    PositionsArrayProperties.RawArray = make(Position2D, 0, PositionsArrayProperties.FixedSize)
```

This fails because `RawArray` contains `Position2D`, not `Position2D` instances.

**Comment by wichert** [comment]
Looking at what `array_init.go.tmpl` does this should be using `{{if $native.IsMarshaler }}*{{ end }}{{ goType $scope $native.Type }}`

**Comment by Danaozhong** [comment]
> Oh no..
> 
> So, I guess `{{ $field.Type }}` needs to be change to `{{ goType $scope $field.Type }}` or `{{ goType $scope $native.Type }} `
> 
> What is the difference between those?

The `native` type is the most fundamental type. For example, if you use `subtype uint32 mytype`, and then use `mytype` in a field, `field` would refer to `mytype`, and `native` refers to `uint32`.

**Comment by Danaozhong** [comment]
@wichert do you have an idea why the CI is not running?

**Comment by jo-me** [comment]
Thanks for the hints!
I've adapted the templates accordingly and I can now execute it against my zserio files (mostly display layer) without generating errors in logs or code.

Please run your test cases again to verify that its working also for your edge cases.

Questions:
- Is Position2D a "native" type because it is a struct type? 
- Why is field.Type wrong in this case? Intuitively, I'd say both types are the same for structs
- What is the reason behind switching back and forth between struct pointers and structs in encoding/decoding of arrays? 

Thanks!

**Comment by wichert** [comment]
> @wichert do you have an idea why the CI is not running?

CI does not run for forks. To trigger CI you can mirror the PR branch into the main repo. That will trigger CI and correctly report it in the PR.

**Review by wichert — APPROVED** [review]
Looks good now!

**Comment by wichert** [comment]
Thanks @jo-me ! I've tagged a new `v0.8.1` release with this change.

**Pull request merged**
